# Generated by Django 6.0.7 on 2026-08-12 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0008_teacherclassassignment'),
        ('accounts', '0005_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس')),
                ('api_url', models.URLField(verbose_name='آدرس API بیگ\u200cبلو\u200cباتن')),
                ('secret', models.CharField(max_length=255, verbose_name='کلید محرمانه API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'تنظیمات BigBlueButton',
                'verbose_name_plural': 'تنظیمات BigBlueButton',
            },
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کلاس آنلاین')),
                ('provider', models.CharField(choices=[('bbb', 'BigBlueButton'), ('skyroom', 'Skyroom')], default='bbb', max_length=20, verbose_name='پلتفرم فعال')),
                ('bbb_room_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه اتاق BBB')),
                ('skyroom_url', models.URLField(blank=True, null=True, verbose_name='لینک جایگزین Skyroom')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_classes', to='academic.academicyear', verbose_name='سال تحصیلی')),
                ('bbb_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_classes', to='online_classes.bbbconfiguration', verbose_name='سرویس BigBlueButton')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('students', models.ManyToManyField(blank=True, related_name='online_classes', to='accounts.studentprofile', verbose_name='دانش\u200cآموزان')),
                ('teachers', models.ManyToManyField(blank=True, related_name='online_classes', to='accounts.teacherprofile', verbose_name='معلم\u200cها')),
            ],
            options={
                'verbose_name': 'کلاس آنلاین',
                'verbose_name_plural': 'کلاس\u200cهای آنلاین',
                'ordering': ('title',),
            },
        ),
    ]
