# Generated by Django 6.0.7 on 2026-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmaterial',
            name='content_type',
            field=models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('link', 'لینک')], default='text', max_length=20, verbose_name='نوع محتوا'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='educational_materials/', verbose_name='فایل'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='متن مطلب'),
        ),
    ]
