# Generated by Django 6.0.7 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_educationalmaterial_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalmaterial',
            name='content_type',
            field=models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('image', 'عکس'), ('video', 'فیلم'), ('link', 'لینک')], default='text', max_length=20, verbose_name='نوع محتوا'),
        ),
    ]
