# Generated by Django 6.0.7 on 2026-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'سوپر ادمین'), ('school_manager', 'مدیر مدرسه'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز'), ('finance', 'امور مالی'), ('operator', 'اپراتور')], default='student', max_length=30, verbose_name='نقش'),
        ),
    ]
