# Generated by Django 6.0.7 on 2026-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام ولی'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس ولی'),
        ),
    ]
