# Generated by Django 6.0.7 on 2026-07-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-title'], 'verbose_name': 'سال تحصیلی', 'verbose_name_plural': 'سالهای تحصیلی'},
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('archived', 'آرشیو')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='سال تحصیلی'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در'),
        ),
    ]
