# Generated by Django 6.0.7 on 2026-07-25 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('name', models.CharField(max_length=50, verbose_name='نام کلاس')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academic.academicyear', verbose_name='سال تحصیلی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academic.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['-academic_year__title', 'grade__order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_classroom_per_academic_year_name')],
            },
        ),
    ]
