# Generated by Django 6.0.7 on 2026-07-26 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_enrollment'),
        ('accounts', '0003_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_per_academic_year',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='unique_active_student_per_academic_year'),
        ),
    ]
