# Generated by Django 6.0.7 on 2026-07-29 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_remove_enrollment_unique_student_per_academic_year_and_more'),
        ('accounts', '0005_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='accounts.teacherprofile', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'تخصیص معلم به کلاس',
                'verbose_name_plural': 'تخصیص معلمان به کلاس\u200cها',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'classroom'), name='unique_teacher_classroom')],
            },
        ),
    ]
