# Generated by Django 6.1 on 2026-08-30 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_classroomschedule'),
        ('accounts', '0007_alter_studentprofile_guardian_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='daily_report_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report_classrooms', to='accounts.teacherprofile', verbose_name='مسئول پیگیری گزارش روزانه'),
        ),
        migrations.CreateModel(
            name='StudentDailyRoutine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('record_date', models.DateField(verbose_name='تاریخ ثبت')),
                ('study_start', models.TimeField(verbose_name='شروع مطالعه')),
                ('study_end', models.TimeField(verbose_name='پایان مطالعه')),
                ('homework_start', models.TimeField(verbose_name='شروع انجام تکالیف')),
                ('homework_end', models.TimeField(verbose_name='پایان انجام تکالیف')),
                ('sleep_time', models.TimeField(verbose_name='ساعت خواب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routines', to='accounts.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'برنامه روزانه دانش\u200cآموز',
                'verbose_name_plural': 'برنامه\u200cهای روزانه دانش\u200cآموزان',
                'ordering': ['-record_date', 'student__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'record_date'), name='unique_student_daily_routine')],
            },
        ),
    ]
