# Generated by Django 6.0.7 on 2026-08-12 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارنامه')),
                ('file', models.FileField(upload_to='report_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل PDF کارنامه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='accounts.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'کارنامه دانش\u200cآموز',
                'verbose_name_plural': 'کارنامه\u200cهای دانش\u200cآموز',
                'ordering': ('-created_at',),
            },
        ),
    ]
