# Generated by Django 6.1 on 2026-08-22 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_last_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('general', 'پیام\u200cهای مدرسه'), ('language', 'واحد زبان')], default='general', max_length=20, verbose_name='بخش گفتگو'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_1', 'participant_2', 'channel'), name='unique_conversation_participants_channel'),
        ),
    ]
