# Generated by Django 6.0.7 on 2026-07-30 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0008_teacherclassassignment'),
        ('accounts', '0005_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تکلیف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='فایل تکلیف')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.classroom', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacherprofile', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
            },
        ),
    ]
