# Generated by Django 6.0.7 on 2026-07-30 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile'),
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='متن پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/', verbose_name='فایل پاسخ')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='تکلیف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='accounts.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ تکلیف',
                'verbose_name_plural': 'پاسخ\u200cهای تکلیف',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_submission')],
            },
        ),
    ]
