# Generated by Django 6.0.7 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentsubmission_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, upload_to='assignments/images/', verbose_name='عکس تکلیف'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='video',
            field=models.FileField(blank=True, upload_to='assignments/videos/', verbose_name='فیلم تکلیف'),
        ),
    ]
