# Generated by Django 6.0.7 on 2026-10-03 15:05

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_image_assignment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='video',
            field=models.FileField(blank=True, upload_to='assignments/videos/', validators=[core.uploads.validate_video], verbose_name='فیلم تکلیف'),
        ),
    ]
