from django.urls import path
from . import views, content_views

urlpatterns = [
    path("teacher/materials/", content_views.teacher_language_content,
         {"kind": "materials"}, name="teacher_language_material_list"),
    path("teacher/assignments/", content_views.teacher_language_content,
         {"kind": "assignments"}, name="teacher_language_assignment_list"),
    path("manage/<uuid:group_id>/content/", content_views.manager_language_group_content,
         name="manager_language_group_content"),
    path("materials/<uuid:material_id>/download/", views.download_language_material, name="download_language_material"),
    path("assignments/<uuid:assignment_id>/download/<str:attachment>/", views.download_language_assignment, name="download_language_assignment"),
    path("", views.student_language_dashboard, name="student_language_dashboard"),
    path("teacher/", views.teacher_language_dashboard, name="teacher_language_dashboard"),
    path("teacher/groups/<uuid:group_id>/", views.language_group_detail, name="language_group_detail"),
    path("teacher/groups/<uuid:group_id>/materials/create/", views.create_language_material,
         name="create_language_material"),
    path("teacher/materials/<uuid:material_id>/edit/", views.edit_language_material,
         name="edit_language_material"),
    path("teacher/groups/<uuid:group_id>/assignments/create/", views.create_language_assignment,
         name="create_language_assignment"),
    path("teacher/assignments/<uuid:assignment_id>/edit/", views.edit_language_assignment,
         name="edit_language_assignment"),
    path("assignments/<uuid:assignment_id>/submit/", views.submit_language_assignment,
         name="submit_language_assignment"),
    path("manage/", views.manage_language_groups, name="manage_language_groups"),
    path("manage/create/", views.language_group_form, name="language_group_create"),
    path("manage/students/search/", views.search_language_students, name="search_language_students"),
    path("manage/<uuid:group_id>/edit/", views.language_group_form, name="language_group_edit"),
    path("manage/<uuid:group_id>/delete/", views.language_group_delete, name="language_group_delete"),
]
