# Generated by Django 6.0.7 on 2026-08-12 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('food_name', models.CharField(max_length=200, verbose_name='نام غذا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'منوی غذا',
                'verbose_name_plural': 'منوهای غذا',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='CafeteriaReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('wants_food', models.BooleanField(default=False, verbose_name='غذا می\u200cخواهد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cafeteria.cafeteriamenu', verbose_name='منوی غذا')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_reservations', to='accounts.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'رزرو غذا',
                'verbose_name_plural': 'رزروهای غذا',
                'constraints': [models.UniqueConstraint(fields=('student', 'menu'), name='unique_student_menu_reservation')],
            },
        ),
    ]
