# Generated by Django 6.0.7 on 2026-08-12 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile'),
        ('cafeteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaReservationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('wants_food', models.BooleanField(default=False, verbose_name='غذا می\u200cخواهد')),
            ],
            options={
                'verbose_name': 'انتخاب غذای روز',
                'verbose_name_plural': 'انتخاب\u200cهای غذای روز',
            },
        ),
        migrations.CreateModel(
            name='CafeteriaWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان هفته')),
                ('start_date', models.DateField(unique=True, verbose_name='تاریخ شروع هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'هفته غذایی',
                'verbose_name_plural': 'هفته\u200cهای غذایی',
                'ordering': ('-start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='cafeteriamenu',
            options={'verbose_name': 'غذای روز', 'verbose_name_plural': 'غذاهای هفته'},
        ),
        migrations.AlterModelOptions(
            name='cafeteriareservation',
            options={'verbose_name': 'رزرو هفتگی غذا', 'verbose_name_plural': 'رزروهای هفتگی غذا'},
        ),
        migrations.RemoveConstraint(
            model_name='cafeteriareservation',
            name='unique_student_menu_reservation',
        ),
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='day',
            field=models.CharField(blank=True, choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه')], max_length=20, null=True, verbose_name='روز هفته'),
        ),
        migrations.AddField(
            model_name='cafeteriareservationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='cafeteriareservationitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='cafeteria.cafeteriamenu', verbose_name='غذای روز'),
        ),
        migrations.AddField(
            model_name='cafeteriareservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafeteria.cafeteriareservation', verbose_name='رزرو هفتگی'),
        ),
        migrations.AddField(
            model_name='cafeteriaweek',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='cafeteria.cafeteriaweek', verbose_name='هفته غذایی'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='cafeteria.cafeteriaweek', verbose_name='هفته غذایی'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriamenu',
            constraint=models.UniqueConstraint(fields=('week', 'day'), name='unique_cafeteria_week_day'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriareservation',
            constraint=models.UniqueConstraint(fields=('student', 'week'), name='unique_student_week_reservation'),
        ),
        migrations.RemoveField(
            model_name='cafeteriareservation',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='cafeteriareservation',
            name='wants_food',
        ),
        migrations.AddConstraint(
            model_name='cafeteriareservationitem',
            constraint=models.UniqueConstraint(fields=('reservation', 'menu'), name='unique_reservation_menu_item'),
        ),
    ]
