# Generated by Django 6.0.7 on 2026-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_cafeteriareservationitem_cafeteriaweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriareservation',
            name='final_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی رزرو'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('zarinpal', 'درگاه زرین\u200cپال'), ('receipt', 'فیش واریزی')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'پرداخت نشده'), ('receipt_pending', 'در انتظار بررسی فیش'), ('paid', 'پرداخت تأیید شده'), ('rejected', 'فیش رد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='cafeteria_receipts/', verbose_name='تصویر فیش واریزی'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='zarinpal_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='cafeteriareservation',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری زرین\u200cپال'),
        ),
    ]
