# Generated by Django 6.0.7 on 2026-09-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafeteria", "0003_cafeteriareservation_final_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeteriaPaymentCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="ایجاد شده در",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="بروزرسانی در",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=32,
                        verbose_name="شماره کارت",
                    ),
                ),
                (
                    "card_holder",
                    models.CharField(
                        max_length=150,
                        verbose_name="نام صاحب کارت",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد کننده",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cards",
                        to="cafeteria.cafeteriaweek",
                        verbose_name="هفته غذایی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کارت واریز",
                "verbose_name_plural": "کارت‌های واریز",
                "ordering": ("created_at",),
            },
        ),
    ]
