# Generated by Django 6.0.7 on 2026-08-04 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('notification_type', models.CharField(choices=[('message', 'پیام جدید'), ('assignment', 'تکلیف جدید'), ('material', 'مطلب آموزشی جدید'), ('announcement', 'اطلاعیه'), ('cafeteria', 'رزرو غذا'), ('system', 'سیستمی')], default='system', max_length=30, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(blank=True, verbose_name='متن اعلان')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='لینک مقصد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
