# Generated by Django 6.0.7 on 2026-08-13 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن اطلاعیه')),
                ('audience', models.CharField(choices=[('all', 'همه'), ('students', 'دانش\u200cآموزان'), ('teachers', 'معلمان')], default='all', max_length=20, verbose_name='مخاطب')),
                ('publish_at', models.DateTimeField(verbose_name='زمان انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'اطلاعیه عمومی',
                'verbose_name_plural': 'اطلاعیه\u200cهای عمومی',
                'ordering': ['-publish_at'],
            },
        ),
    ]
