# Generated by Django 6.0.7 on 2026-08-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_teacherclassassignment'),
        ('notifications', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='academic.classroom', verbose_name='کلاس مخاطب'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'همه'), ('students', 'دانش\u200cآموزان'), ('teachers', 'معلمان'), ('classroom', 'یک کلاس خاص')], default='all', max_length=20, verbose_name='مخاطب'),
        ),
    ]
