# Generated by Django 6.0.7 on 2026-10-02 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_announcement_classroom_alter_announcement_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر JPG، PNG، WebP یا GIF؛ برای اطلاعیه متنی، این بخش را خالی بگذارید.', upload_to='announcements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='تصویر اطلاعیه (اختیاری)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.announcement', verbose_name='اطلاعیه مرتبط'),
        ),
    ]
