# Generated by Django 6.0.7 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_classroom_daily_report_responsible_and_more'),
        ('accounts', '0007_alter_studentprofile_guardian_name_and_more'),
        ('notifications', '0004_announcement_image_notification_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to='academic.classroom', verbose_name='کلاس\u200cهای مخاطب'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='targeted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to='accounts.teacherprofile', verbose_name='معلمان مخاطب'),
        ),
    ]
