# Generated by Django 6.0.7 on 2026-10-03 14:58

from django.conf import settings
from django.db import migrations, models


def record_existing_deliveries(apps, schema_editor):
    Announcement = apps.get_model("notifications", "Announcement")
    Notification = apps.get_model("notifications", "Notification")
    for announcement in Announcement.objects.all().iterator():
        announcement.notified_users.add(*Notification.objects.filter(
            announcement=announcement).values_list("recipient_id", flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_announcement_classrooms_announcement_targeted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='notified_users',
            field=models.ManyToManyField(blank=True, editable=False, related_name='delivered_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(record_existing_deliveries, migrations.RunPython.noop),
    ]
