# Generated by Django 6.1 on 2026-08-22 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0009_academicyear_unique_active_academic_year'),
        ('accounts', '0007_alter_studentprofile_guardian_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان گروه زبان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_groups', to='academic.academicyear', verbose_name='سال تحصیلی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('students', models.ManyToManyField(related_name='language_groups', to='accounts.studentprofile', verbose_name='دانش\u200cآموزان')),
                ('teachers', models.ManyToManyField(related_name='language_groups', to='accounts.teacherprofile', verbose_name='معلمان زبان')),
            ],
            options={
                'verbose_name': 'گروه زبان',
                'verbose_name_plural': 'گروه\u200cهای زبان',
                'ordering': ('-academic_year__title', 'title'),
            },
        ),
        migrations.CreateModel(
            name='LanguageAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تکلیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='language_assignments/', verbose_name='فایل تکلیف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_assignments', to='accounts.teacherprofile', verbose_name='معلم زبان')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='language_unit.languagegroup', verbose_name='گروه زبان')),
            ],
            options={
                'verbose_name': 'تکلیف واحد زبان',
                'verbose_name_plural': 'تکالیف واحد زبان',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LanguageMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content_type', models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('link', 'لینک')], default='text', max_length=20, verbose_name='نوع محتوا')),
                ('content', models.TextField(blank=True, verbose_name='متن مطلب')),
                ('file', models.FileField(blank=True, null=True, upload_to='language_materials/', verbose_name='فایل')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='language_unit.languagegroup', verbose_name='گروه زبان')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_materials', to='accounts.teacherprofile', verbose_name='معلم زبان')),
            ],
            options={
                'verbose_name': 'مطلب واحد زبان',
                'verbose_name_plural': 'مطالب واحد زبان',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LanguageAssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی در')),
                ('answer_text', models.TextField(blank=True, verbose_name='متن پاسخ')),
                ('file', models.FileField(blank=True, null=True, upload_to='language_submissions/', verbose_name='فایل پاسخ')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='language_unit.languageassignment', verbose_name='تکلیف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_submissions', to='accounts.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ تکلیف زبان',
                'verbose_name_plural': 'پاسخ\u200cهای تکلیف زبان',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_language_assignment_submission')],
            },
        ),
        migrations.AddConstraint(
            model_name='languagegroup',
            constraint=models.UniqueConstraint(fields=('academic_year', 'title'), name='unique_language_group_per_year'),
        ),
    ]
