# Generated by Django 6.0.7 on 2026-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageassignment',
            name='image',
            field=models.ImageField(blank=True, upload_to='language_assignments/images/', verbose_name='عکس تکلیف'),
        ),
        migrations.AddField(
            model_name='languageassignment',
            name='video',
            field=models.FileField(blank=True, upload_to='language_assignments/videos/', verbose_name='فیلم تکلیف'),
        ),
        migrations.AlterField(
            model_name='languagematerial',
            name='content_type',
            field=models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('image', 'عکس'), ('video', 'فیلم'), ('link', 'لینک')], default='text', max_length=20, verbose_name='نوع محتوا'),
        ),
    ]
