# Generated by Django 6.0.7 on 2026-10-03 15:05

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_unit', '0002_languageassignment_image_languageassignment_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageassignment',
            name='video',
            field=models.FileField(blank=True, upload_to='language_assignments/videos/', validators=[core.uploads.validate_video], verbose_name='فیلم تکلیف'),
        ),
    ]
